### PR TITLE
Fix page refreshing when enter key is pressed on form input #6

### PR DESCRIPTION
**Pull request by luciandragomir**

### CODE REVIEW

**Comment by luciandragomir** [comment]
Fixes #6

**Comment by mookman288** [comment]
Hi Lucian, 

Thanks for your help. I really do appreciate it! Could you explain the PR? How would onsubmit affect detecting when someone is typing into an input?

**Comment by luciandragomir** [comment]
I think the issue happened when the user presses the Enter key, which triggers the form to be submitted.
The default browser behavior is to send all the form data to a url specified in the _action_ attribute of the form (which in this case there is none). If there is no action mentioned, it will do a postback which causes the browser to refresh.

**Comment by mookman288** [comment]
That's very possible, but the individual who reported this bug said they weren't pressing enter; it was just triggering the phrase and refreshing with a `?` added to the url. I'll ask them to do more testing once I have time to merge this in.

**Comment by luciandragomir** [comment]
I only managed to reproduce it by the enter key. If you find other steps to reproduce I will gladly submit another PR

**Comment by mookman288** [comment]
Yeah, I could not reproduce this myself, but at the same time if it's occurring for anyone that defeats the purpose of the lib. 

Thank you again for your PR. It's definitely appreciated.

**Pull request closed without merging**
